services:
  parser.jsonparser:
    arguments:
      - '@grumphp.util.filesystem'
      - '@json.parser'
    class: Pnnl\PrettyJSONYAML\Parser\JsonParser
  parser.yamlparser:
    arguments:
      - '@grumphp.util.filesystem'
    class: Pnnl\PrettyJSONYAML\Parser\YamlParser
