services:
  Pnnl\PrettyJSONYAML\Task\PrettyJson:
    arguments:
      - '@linter.jsonprettylinter'
    class: Pnnl\PrettyJSONYAML\Task\PrettyJson
    tags:
      - name: grumphp.task
        task: prettyjson
  Pnnl\PrettyJSONYAML\Task\PrettyYaml:
    arguments:
      - '@linter.yamlprettylinter'
    class: Pnnl\PrettyJSONYAML\Task\PrettyYaml
    tags:
      - name: grumphp.task
        task: prettyyaml
