after_success:
  - 'travis_retry php vendor/bin/php-coveralls'
before_script:
  - 'composer self-update'
  - 'composer install'
dist: trusty
git:
  depth: 5
language: php
matrix:
  allow_failures:
    - php: nightly
  fast_finish: true
php:
  - 5.6
  - 7.0
  - 7.1
  - nightly
script:
  - 'composer test'
sudo: false
